export enum AwsResourceEnum {
    EC2 = "instance",
    S3 = "s3_bucket",
    DYNAMO_DB = "dynamo_db_table",
    CLOUDFRONT = "cloudfront_distribution",
    SECURITY_GROUP = "security_group",
    RDS = "rds_instance",
    ECS = "ecs_cluster",
    LAUNCH_CONFIG = "launch_configuration",
    VPC = "vpc",
    SUBNET = "subnet",
    ACS = "auto_scaling_group",
    DB_SUBNET = "db_subnet_group",
    DOC_DB_CLUSTER = "documentdb_cluster",
    DOC_DB_CLUS_INSTANCE = "documentdb_cluster_instance",
    DOC_DB_INSTANCE = "db_instance",
}